-- AHM.AHMSDNIS_MSTBRND definition

CREATE TABLE `AHMSDNIS_MSTBRND` (
  `VBRNDCD` varchar(5) NOT NULL,
  `VBRNDNM` varchar(25) NOT NULL,
  `VBRNDTYP` varchar(10) NOT NULL,
  `VURLBRND` varchar(255) NOT NULL,
  `DBGNEFF` date DEFAULT NULL,
  `DLASTEFF` date DEFAULT NULL,
  `VCREA` varchar(15) DEFAULT NULL,
  `DCREA` date DEFAULT NULL,
  `VMODI` varchar(15) DEFAULT NULL,
  `DMODI` date DEFAULT NULL,
  PRIMARY KEY (`VBRNDCD`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;